DROP DATABASE IF EXISTS admision;
CREATE DATABASE admision CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE admision;

CREATE TABLE aspirante (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  ci VARCHAR(50) NOT NULL,
  telefono VARCHAR(50),
  registrado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE pago (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  aspirante_id BIGINT NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  metodo ENUM('TARJETA','TRANSFERENCIA','VENTANILLA') NOT NULL,
  estado ENUM('CONFIRMADO','RECHAZADO','PENDIENTE') NOT NULL,
  transaccion VARCHAR(100),
  pagado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pago_asp FOREIGN KEY (aspirante_id) REFERENCES aspirante(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE carrera (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(150) NOT NULL,
  activa TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE aspirante_carrera (
  aspirante_id BIGINT PRIMARY KEY,
  carrera_id BIGINT NOT NULL,
  seleccionado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ac_asp FOREIGN KEY (aspirante_id) REFERENCES aspirante(id) ON DELETE CASCADE,
  CONSTRAINT fk_ac_car FOREIGN KEY (carrera_id) REFERENCES carrera(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE documento (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  aspirante_id BIGINT NOT NULL,
  tipo ENUM('FOTO','CERTIFICADO','CI') NOT NULL,
  nombre_archivo VARCHAR(255) NOT NULL,
  mime VARCHAR(100) NOT NULL,
  tamano_bytes BIGINT NOT NULL,
  ruta VARCHAR(500) NOT NULL,
  subido_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_doc_asp FOREIGN KEY (aspirante_id) REFERENCES aspirante(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE examen (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(150) NOT NULL,
  duracion_min INT NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE pregunta (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  examen_id BIGINT NOT NULL,
  enunciado TEXT NOT NULL,
  tipo ENUM('OPCION_MULTIPLE','ABIERTA') NOT NULL DEFAULT 'OPCION_MULTIPLE',
  CONSTRAINT fk_preg_ex FOREIGN KEY (examen_id) REFERENCES examen(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE opcion (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  pregunta_id BIGINT NOT NULL,
  texto VARCHAR(500) NOT NULL,
  correcta TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_opt_pre FOREIGN KEY (pregunta_id) REFERENCES pregunta(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE respuesta (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  examen_id BIGINT NOT NULL,
  pregunta_id BIGINT NOT NULL,
  aspirante_id BIGINT NOT NULL,
  opcion_id BIGINT NULL,
  texto TEXT NULL,
  guardado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_resp (examen_id, pregunta_id, aspirante_id),
  CONSTRAINT fk_resp_ex FOREIGN KEY (examen_id) REFERENCES examen(id) ON DELETE CASCADE,
  CONSTRAINT fk_resp_pre FOREIGN KEY (pregunta_id) REFERENCES pregunta(id) ON DELETE CASCADE,
  CONSTRAINT fk_resp_asp FOREIGN KEY (aspirante_id) REFERENCES aspirante(id) ON DELETE CASCADE,
  CONSTRAINT fk_resp_opt FOREIGN KEY (opcion_id) REFERENCES opcion(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE calificacion (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  aspirante_id BIGINT NOT NULL,
  examen_id BIGINT NOT NULL,
  puntaje INT NOT NULL,
  max_puntaje INT NOT NULL,
  calificado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_cal (aspirante_id, examen_id),
  CONSTRAINT fk_cal_asp FOREIGN KEY (aspirante_id) REFERENCES aspirante(id) ON DELETE CASCADE,
  CONSTRAINT fk_cal_ex FOREIGN KEY (examen_id) REFERENCES examen(id) ON DELETE CASCADE
) ENGINE=InnoDB;
